
tasks:
  - init: npm install && npm run build && make



vscode:
  extensions:
    - TabNine.tabnine-vscode
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - init: npm install && npm run build && make


